CREATE TABLE helmet_events
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_type       VARCHAR(255)                            NOT NULL,
    date_time        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    duration         INTEGER                                 NOT NULL,
    image_url        VARCHAR(255)                            NOT NULL,
    parent_event_id  BIGINT,
    metric_date_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_helmet_events PRIMARY KEY (id)
);

CREATE TABLE metrics
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_time   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    temperature FLOAT                                   NOT NULL,
    humidity    FLOAT                                   NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_metrics PRIMARY KEY (id)
);

CREATE TABLE users
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255)                            NOT NULL,
    last_name       VARCHAR(255)                            NOT NULL,
    email           VARCHAR(255)                            NOT NULL,
    hashed_password VARCHAR(255)                            NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE metrics
    ADD CONSTRAINT UK_METRICS_DATE_TIME UNIQUE (date_time);

ALTER TABLE helmet_events
    ADD CONSTRAINT uc_helmet_events_parent_event UNIQUE (parent_event_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_name UNIQUE (name);

ALTER TABLE helmet_events
    ADD CONSTRAINT FK_HELMET_EVENTS_ON_METRIC_DATE_TIME FOREIGN KEY (metric_date_time) REFERENCES metrics (date_time);

ALTER TABLE helmet_events
    ADD CONSTRAINT FK_HELMET_EVENTS_ON_PARENT_EVENT FOREIGN KEY (parent_event_id) REFERENCES helmet_events (id);