CREATE TABLE data
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_time   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    temperature FLOAT                                   NOT NULL,
    humidity    FLOAT                                   NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_data PRIMARY KEY (id)
);

CREATE TABLE helmet_events
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_type      VARCHAR(255)                            NOT NULL,
    duration        INTEGER                                 NOT NULL,
    image           VARCHAR(255)                            NOT NULL,
    parent_event_id BIGINT,
    date_time       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_helmet_events PRIMARY KEY (id)
);

CREATE TABLE users
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255)                            NOT NULL,
    last_name       VARCHAR(255)                            NOT NULL,
    email           VARCHAR(255)                            NOT NULL,
    hashed_password VARCHAR(255)                            NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE data
    ADD CONSTRAINT UK_DATA_DATE_TIME UNIQUE (date_time);

ALTER TABLE helmet_events
    ADD CONSTRAINT uc_helmet_events_parent_event UNIQUE (parent_event_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_name UNIQUE (name);

ALTER TABLE helmet_events
    ADD CONSTRAINT FK_HELMET_EVENTS_ON_DATE_TIME FOREIGN KEY (date_time) REFERENCES data (date_time);

ALTER TABLE helmet_events
    ADD CONSTRAINT FK_HELMET_EVENTS_ON_PARENT_EVENT FOREIGN KEY (parent_event_id) REFERENCES helmet_events (id);